// <auto-generated />
using System;
using Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.Modelos.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Amazonas"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Ancash"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Apurímac"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Arequipa"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Ayacucho"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Cajamarca"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Callao"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Cusco"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Huancavelica"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Huánuco"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Ica"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Junín"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "La Libertad"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Lambayeque"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Lima"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Loreto"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Madre de Dios"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Moquegua"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Pasco"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Piura"
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Puno"
                        });
                });

            modelBuilder.Entity("Data.Modelos.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Provincias");

                    b.HasData(
                        new
                        {
                            Id = 130,
                            DepartamentoId = 1,
                            Nombre = "Chachapoyas"
                        },
                        new
                        {
                            Id = 131,
                            DepartamentoId = 1,
                            Nombre = "Bagua"
                        },
                        new
                        {
                            Id = 132,
                            DepartamentoId = 1,
                            Nombre = "Bongará"
                        },
                        new
                        {
                            Id = 133,
                            DepartamentoId = 1,
                            Nombre = "Condorcanqui"
                        },
                        new
                        {
                            Id = 134,
                            DepartamentoId = 1,
                            Nombre = "Luya"
                        },
                        new
                        {
                            Id = 135,
                            DepartamentoId = 1,
                            Nombre = "Rodríguez de Mendoza"
                        },
                        new
                        {
                            Id = 136,
                            DepartamentoId = 1,
                            Nombre = "Utcubamba"
                        },
                        new
                        {
                            Id = 137,
                            DepartamentoId = 2,
                            Nombre = "Huaraz"
                        },
                        new
                        {
                            Id = 138,
                            DepartamentoId = 2,
                            Nombre = "Aija"
                        },
                        new
                        {
                            Id = 139,
                            DepartamentoId = 2,
                            Nombre = "Antonio Raymondi"
                        },
                        new
                        {
                            Id = 140,
                            DepartamentoId = 2,
                            Nombre = "Asunción"
                        },
                        new
                        {
                            Id = 141,
                            DepartamentoId = 2,
                            Nombre = "Bolognesi"
                        },
                        new
                        {
                            Id = 142,
                            DepartamentoId = 2,
                            Nombre = "Carhuaz"
                        },
                        new
                        {
                            Id = 143,
                            DepartamentoId = 2,
                            Nombre = "Carlos F"
                        },
                        new
                        {
                            Id = 144,
                            DepartamentoId = 2,
                            Nombre = "Fitzcarrald"
                        },
                        new
                        {
                            Id = 145,
                            DepartamentoId = 2,
                            Nombre = "Casma"
                        },
                        new
                        {
                            Id = 146,
                            DepartamentoId = 2,
                            Nombre = "Corongo"
                        },
                        new
                        {
                            Id = 147,
                            DepartamentoId = 2,
                            Nombre = "Huari"
                        },
                        new
                        {
                            Id = 148,
                            DepartamentoId = 2,
                            Nombre = "Huarmey"
                        },
                        new
                        {
                            Id = 149,
                            DepartamentoId = 2,
                            Nombre = "Huaylas"
                        },
                        new
                        {
                            Id = 150,
                            DepartamentoId = 2,
                            Nombre = "Mariscal Luzuriaga"
                        },
                        new
                        {
                            Id = 151,
                            DepartamentoId = 2,
                            Nombre = "Ocros"
                        },
                        new
                        {
                            Id = 152,
                            DepartamentoId = 2,
                            Nombre = "Pallasca"
                        },
                        new
                        {
                            Id = 153,
                            DepartamentoId = 2,
                            Nombre = "Pomabamba"
                        },
                        new
                        {
                            Id = 154,
                            DepartamentoId = 2,
                            Nombre = "Recuay"
                        },
                        new
                        {
                            Id = 155,
                            DepartamentoId = 2,
                            Nombre = "Santa"
                        },
                        new
                        {
                            Id = 156,
                            DepartamentoId = 2,
                            Nombre = "Sihuas"
                        },
                        new
                        {
                            Id = 157,
                            DepartamentoId = 2,
                            Nombre = "Yungay"
                        },
                        new
                        {
                            Id = 158,
                            DepartamentoId = 3,
                            Nombre = "Abancay"
                        },
                        new
                        {
                            Id = 159,
                            DepartamentoId = 3,
                            Nombre = "Antabamba"
                        },
                        new
                        {
                            Id = 160,
                            DepartamentoId = 3,
                            Nombre = "Aymaraes"
                        },
                        new
                        {
                            Id = 161,
                            DepartamentoId = 3,
                            Nombre = "Cotabambas"
                        },
                        new
                        {
                            Id = 162,
                            DepartamentoId = 3,
                            Nombre = "Grau"
                        },
                        new
                        {
                            Id = 163,
                            DepartamentoId = 3,
                            Nombre = "Chincheros"
                        },
                        new
                        {
                            Id = 164,
                            DepartamentoId = 3,
                            Nombre = "Andahuaylas"
                        },
                        new
                        {
                            Id = 165,
                            DepartamentoId = 4,
                            Nombre = "Arequipa"
                        },
                        new
                        {
                            Id = 166,
                            DepartamentoId = 4,
                            Nombre = "Camaná"
                        },
                        new
                        {
                            Id = 167,
                            DepartamentoId = 4,
                            Nombre = "Caravelí"
                        },
                        new
                        {
                            Id = 168,
                            DepartamentoId = 4,
                            Nombre = "Castilla"
                        },
                        new
                        {
                            Id = 169,
                            DepartamentoId = 4,
                            Nombre = "Caylloma"
                        },
                        new
                        {
                            Id = 170,
                            DepartamentoId = 4,
                            Nombre = "Condesuyos"
                        },
                        new
                        {
                            Id = 171,
                            DepartamentoId = 4,
                            Nombre = "Islay"
                        },
                        new
                        {
                            Id = 172,
                            DepartamentoId = 4,
                            Nombre = "La Unión"
                        },
                        new
                        {
                            Id = 1,
                            DepartamentoId = 5,
                            Nombre = "Cangallo"
                        },
                        new
                        {
                            Id = 2,
                            DepartamentoId = 5,
                            Nombre = "Huanta"
                        },
                        new
                        {
                            Id = 3,
                            DepartamentoId = 5,
                            Nombre = "Huamanga"
                        },
                        new
                        {
                            Id = 4,
                            DepartamentoId = 5,
                            Nombre = "Huanca Sancos"
                        },
                        new
                        {
                            Id = 5,
                            DepartamentoId = 5,
                            Nombre = "La Mar"
                        },
                        new
                        {
                            Id = 6,
                            DepartamentoId = 5,
                            Nombre = "Lucanas"
                        },
                        new
                        {
                            Id = 7,
                            DepartamentoId = 5,
                            Nombre = "Parinacochas"
                        },
                        new
                        {
                            Id = 8,
                            DepartamentoId = 5,
                            Nombre = "Páucar del Sara Sara"
                        },
                        new
                        {
                            Id = 9,
                            DepartamentoId = 5,
                            Nombre = "Sucre"
                        },
                        new
                        {
                            Id = 10,
                            DepartamentoId = 5,
                            Nombre = "Víctor Fajardo"
                        },
                        new
                        {
                            Id = 11,
                            DepartamentoId = 5,
                            Nombre = "Vilcashuamán"
                        },
                        new
                        {
                            Id = 12,
                            DepartamentoId = 6,
                            Nombre = "Cajamarca"
                        },
                        new
                        {
                            Id = 13,
                            DepartamentoId = 6,
                            Nombre = "Cajabamba"
                        },
                        new
                        {
                            Id = 14,
                            DepartamentoId = 6,
                            Nombre = "Celendín"
                        },
                        new
                        {
                            Id = 15,
                            DepartamentoId = 6,
                            Nombre = "Chota"
                        },
                        new
                        {
                            Id = 16,
                            DepartamentoId = 6,
                            Nombre = "Contumazá"
                        },
                        new
                        {
                            Id = 17,
                            DepartamentoId = 6,
                            Nombre = "Cutervo"
                        },
                        new
                        {
                            Id = 18,
                            DepartamentoId = 6,
                            Nombre = "Hualgayoc"
                        },
                        new
                        {
                            Id = 19,
                            DepartamentoId = 6,
                            Nombre = "Jaén"
                        },
                        new
                        {
                            Id = 20,
                            DepartamentoId = 6,
                            Nombre = "San Ignacio"
                        },
                        new
                        {
                            Id = 21,
                            DepartamentoId = 6,
                            Nombre = "San Marcos"
                        },
                        new
                        {
                            Id = 22,
                            DepartamentoId = 6,
                            Nombre = "San Miguel"
                        },
                        new
                        {
                            Id = 23,
                            DepartamentoId = 6,
                            Nombre = "San Pablo"
                        },
                        new
                        {
                            Id = 24,
                            DepartamentoId = 6,
                            Nombre = "Santa Cruz"
                        },
                        new
                        {
                            Id = 25,
                            DepartamentoId = 7,
                            Nombre = "Callao"
                        },
                        new
                        {
                            Id = 26,
                            DepartamentoId = 8,
                            Nombre = "Cuzco"
                        },
                        new
                        {
                            Id = 27,
                            DepartamentoId = 8,
                            Nombre = "Acomayo"
                        },
                        new
                        {
                            Id = 28,
                            DepartamentoId = 8,
                            Nombre = "Anta"
                        },
                        new
                        {
                            Id = 29,
                            DepartamentoId = 8,
                            Nombre = "Calca"
                        },
                        new
                        {
                            Id = 30,
                            DepartamentoId = 8,
                            Nombre = "Canas"
                        },
                        new
                        {
                            Id = 31,
                            DepartamentoId = 8,
                            Nombre = "Canchis"
                        },
                        new
                        {
                            Id = 32,
                            DepartamentoId = 8,
                            Nombre = "Chumbivilcas"
                        },
                        new
                        {
                            Id = 33,
                            DepartamentoId = 8,
                            Nombre = "Espinar"
                        },
                        new
                        {
                            Id = 34,
                            DepartamentoId = 8,
                            Nombre = "La Convención"
                        },
                        new
                        {
                            Id = 35,
                            DepartamentoId = 8,
                            Nombre = "Paruro"
                        },
                        new
                        {
                            Id = 36,
                            DepartamentoId = 8,
                            Nombre = "Paucartambo"
                        },
                        new
                        {
                            Id = 37,
                            DepartamentoId = 8,
                            Nombre = "Quispicanchi"
                        },
                        new
                        {
                            Id = 38,
                            DepartamentoId = 8,
                            Nombre = "Urubamba"
                        },
                        new
                        {
                            Id = 39,
                            DepartamentoId = 9,
                            Nombre = "Huancavelica"
                        },
                        new
                        {
                            Id = 40,
                            DepartamentoId = 9,
                            Nombre = "Acobamba"
                        },
                        new
                        {
                            Id = 41,
                            DepartamentoId = 9,
                            Nombre = "Angaraes"
                        },
                        new
                        {
                            Id = 42,
                            DepartamentoId = 9,
                            Nombre = "Castrovirreyna"
                        },
                        new
                        {
                            Id = 43,
                            DepartamentoId = 9,
                            Nombre = "Churcampa"
                        },
                        new
                        {
                            Id = 44,
                            DepartamentoId = 9,
                            Nombre = "Huaytará"
                        },
                        new
                        {
                            Id = 45,
                            DepartamentoId = 9,
                            Nombre = "Tayacaja"
                        },
                        new
                        {
                            Id = 46,
                            DepartamentoId = 10,
                            Nombre = "Huánuco"
                        },
                        new
                        {
                            Id = 47,
                            DepartamentoId = 10,
                            Nombre = "Ambo"
                        },
                        new
                        {
                            Id = 48,
                            DepartamentoId = 10,
                            Nombre = "Dos de Mayo"
                        },
                        new
                        {
                            Id = 49,
                            DepartamentoId = 10,
                            Nombre = "Huacaybamba"
                        },
                        new
                        {
                            Id = 50,
                            DepartamentoId = 10,
                            Nombre = "Huamalíes"
                        },
                        new
                        {
                            Id = 51,
                            DepartamentoId = 10,
                            Nombre = "Leoncio Prado"
                        },
                        new
                        {
                            Id = 52,
                            DepartamentoId = 10,
                            Nombre = "Marañón"
                        },
                        new
                        {
                            Id = 53,
                            DepartamentoId = 10,
                            Nombre = "Pachitea"
                        },
                        new
                        {
                            Id = 54,
                            DepartamentoId = 10,
                            Nombre = "Puerto Inca"
                        },
                        new
                        {
                            Id = 55,
                            DepartamentoId = 10,
                            Nombre = "Lauricocha"
                        },
                        new
                        {
                            Id = 56,
                            DepartamentoId = 10,
                            Nombre = "Yarowilca"
                        },
                        new
                        {
                            Id = 57,
                            DepartamentoId = 11,
                            Nombre = "Ica"
                        },
                        new
                        {
                            Id = 58,
                            DepartamentoId = 11,
                            Nombre = "Chincha"
                        },
                        new
                        {
                            Id = 59,
                            DepartamentoId = 11,
                            Nombre = "Nazca"
                        },
                        new
                        {
                            Id = 60,
                            DepartamentoId = 11,
                            Nombre = "Palpa"
                        },
                        new
                        {
                            Id = 61,
                            DepartamentoId = 11,
                            Nombre = "Pisco"
                        },
                        new
                        {
                            Id = 62,
                            DepartamentoId = 12,
                            Nombre = "Chanchamayo"
                        },
                        new
                        {
                            Id = 63,
                            DepartamentoId = 12,
                            Nombre = "Chupaca"
                        },
                        new
                        {
                            Id = 64,
                            DepartamentoId = 12,
                            Nombre = "Concepción"
                        },
                        new
                        {
                            Id = 65,
                            DepartamentoId = 12,
                            Nombre = "Huancayo"
                        },
                        new
                        {
                            Id = 66,
                            DepartamentoId = 12,
                            Nombre = "Jauja"
                        },
                        new
                        {
                            Id = 67,
                            DepartamentoId = 12,
                            Nombre = "Junín"
                        },
                        new
                        {
                            Id = 68,
                            DepartamentoId = 12,
                            Nombre = "Satipo"
                        },
                        new
                        {
                            Id = 69,
                            DepartamentoId = 12,
                            Nombre = "Tarma"
                        },
                        new
                        {
                            Id = 70,
                            DepartamentoId = 12,
                            Nombre = "Yauli"
                        },
                        new
                        {
                            Id = 71,
                            DepartamentoId = 13,
                            Nombre = "Trujillo"
                        },
                        new
                        {
                            Id = 72,
                            DepartamentoId = 13,
                            Nombre = "Ascope"
                        },
                        new
                        {
                            Id = 73,
                            DepartamentoId = 13,
                            Nombre = "Bolívar"
                        },
                        new
                        {
                            Id = 74,
                            DepartamentoId = 13,
                            Nombre = "Chepén"
                        },
                        new
                        {
                            Id = 75,
                            DepartamentoId = 13,
                            Nombre = "Julcán"
                        },
                        new
                        {
                            Id = 76,
                            DepartamentoId = 13,
                            Nombre = "Otuzco"
                        },
                        new
                        {
                            Id = 77,
                            DepartamentoId = 13,
                            Nombre = "Gran Chimú"
                        },
                        new
                        {
                            Id = 78,
                            DepartamentoId = 13,
                            Nombre = "Pacasmayo"
                        },
                        new
                        {
                            Id = 79,
                            DepartamentoId = 13,
                            Nombre = "Pataz"
                        },
                        new
                        {
                            Id = 80,
                            DepartamentoId = 13,
                            Nombre = "Sánchez Carrión"
                        },
                        new
                        {
                            Id = 81,
                            DepartamentoId = 13,
                            Nombre = "Santiago de Chuco"
                        },
                        new
                        {
                            Id = 82,
                            DepartamentoId = 13,
                            Nombre = "Virú"
                        },
                        new
                        {
                            Id = 83,
                            DepartamentoId = 14,
                            Nombre = "Chiclayo"
                        },
                        new
                        {
                            Id = 84,
                            DepartamentoId = 14,
                            Nombre = "Ferreñafe"
                        },
                        new
                        {
                            Id = 85,
                            DepartamentoId = 14,
                            Nombre = "Lambayeque"
                        },
                        new
                        {
                            Id = 86,
                            DepartamentoId = 15,
                            Nombre = "Barranca"
                        },
                        new
                        {
                            Id = 87,
                            DepartamentoId = 15,
                            Nombre = "Cajatambo"
                        },
                        new
                        {
                            Id = 88,
                            DepartamentoId = 15,
                            Nombre = "Canta"
                        },
                        new
                        {
                            Id = 89,
                            DepartamentoId = 15,
                            Nombre = "Cañete"
                        },
                        new
                        {
                            Id = 90,
                            DepartamentoId = 15,
                            Nombre = "Huaral"
                        },
                        new
                        {
                            Id = 91,
                            DepartamentoId = 15,
                            Nombre = "Huarochirí"
                        },
                        new
                        {
                            Id = 92,
                            DepartamentoId = 15,
                            Nombre = "Huaura"
                        },
                        new
                        {
                            Id = 93,
                            DepartamentoId = 15,
                            Nombre = "Lima"
                        },
                        new
                        {
                            Id = 94,
                            DepartamentoId = 15,
                            Nombre = "Oyón"
                        },
                        new
                        {
                            Id = 95,
                            DepartamentoId = 15,
                            Nombre = "Yauyos"
                        },
                        new
                        {
                            Id = 96,
                            DepartamentoId = 16,
                            Nombre = "Maynas"
                        },
                        new
                        {
                            Id = 97,
                            DepartamentoId = 16,
                            Nombre = "Putumayo"
                        },
                        new
                        {
                            Id = 98,
                            DepartamentoId = 16,
                            Nombre = "Alto Amazonas"
                        },
                        new
                        {
                            Id = 99,
                            DepartamentoId = 16,
                            Nombre = "Loreto"
                        },
                        new
                        {
                            Id = 100,
                            DepartamentoId = 16,
                            Nombre = "Mariscal Ramón Castilla"
                        },
                        new
                        {
                            Id = 101,
                            DepartamentoId = 16,
                            Nombre = "Requena"
                        },
                        new
                        {
                            Id = 102,
                            DepartamentoId = 16,
                            Nombre = "Ucayali"
                        },
                        new
                        {
                            Id = 103,
                            DepartamentoId = 16,
                            Nombre = "Datem del Marañón"
                        },
                        new
                        {
                            Id = 104,
                            DepartamentoId = 17,
                            Nombre = "Tambopata"
                        },
                        new
                        {
                            Id = 105,
                            DepartamentoId = 17,
                            Nombre = "Manu"
                        },
                        new
                        {
                            Id = 106,
                            DepartamentoId = 17,
                            Nombre = "Tahuamanu"
                        },
                        new
                        {
                            Id = 107,
                            DepartamentoId = 18,
                            Nombre = "Mariscal Nieto"
                        },
                        new
                        {
                            Id = 108,
                            DepartamentoId = 18,
                            Nombre = "General Sánchez Cerro"
                        },
                        new
                        {
                            Id = 109,
                            DepartamentoId = 18,
                            Nombre = "Ilo"
                        },
                        new
                        {
                            Id = 110,
                            DepartamentoId = 19,
                            Nombre = "Pasco"
                        },
                        new
                        {
                            Id = 111,
                            DepartamentoId = 19,
                            Nombre = "Oxapampa"
                        },
                        new
                        {
                            Id = 112,
                            DepartamentoId = 19,
                            Nombre = "Daniel A"
                        },
                        new
                        {
                            Id = 113,
                            DepartamentoId = 19,
                            Nombre = "Carrión"
                        },
                        new
                        {
                            Id = 114,
                            DepartamentoId = 20,
                            Nombre = "Ayabaca"
                        },
                        new
                        {
                            Id = 115,
                            DepartamentoId = 20,
                            Nombre = "Huancabamba"
                        },
                        new
                        {
                            Id = 116,
                            DepartamentoId = 20,
                            Nombre = "Morropón"
                        },
                        new
                        {
                            Id = 117,
                            DepartamentoId = 20,
                            Nombre = "Piura"
                        },
                        new
                        {
                            Id = 118,
                            DepartamentoId = 20,
                            Nombre = "Sechura"
                        },
                        new
                        {
                            Id = 119,
                            DepartamentoId = 20,
                            Nombre = "Sullana"
                        },
                        new
                        {
                            Id = 120,
                            DepartamentoId = 20,
                            Nombre = "Paita"
                        },
                        new
                        {
                            Id = 121,
                            DepartamentoId = 20,
                            Nombre = "Talara"
                        },
                        new
                        {
                            Id = 122,
                            DepartamentoId = 21,
                            Nombre = "San Román"
                        },
                        new
                        {
                            Id = 123,
                            DepartamentoId = 21,
                            Nombre = "Puno"
                        },
                        new
                        {
                            Id = 124,
                            DepartamentoId = 21,
                            Nombre = "Azángaro"
                        },
                        new
                        {
                            Id = 125,
                            DepartamentoId = 21,
                            Nombre = "Chucuito"
                        },
                        new
                        {
                            Id = 126,
                            DepartamentoId = 21,
                            Nombre = "El Collao"
                        },
                        new
                        {
                            Id = 127,
                            DepartamentoId = 21,
                            Nombre = "Melgar"
                        },
                        new
                        {
                            Id = 128,
                            DepartamentoId = 21,
                            Nombre = "Carabaya"
                        },
                        new
                        {
                            Id = 129,
                            DepartamentoId = 21,
                            Nombre = "Huancané"
                        });
                });

            modelBuilder.Entity("Data.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NumeroDocumento")
                        .HasColumnType("bigint");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int");

                    b.Property<bool>("Sexo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("NumeroDocumento")
                        .IsUnique();

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Data.Modelos.Provincia", b =>
                {
                    b.HasOne("Data.Modelos.Departamento", null)
                        .WithMany("Provincias")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Modelos.Usuario", b =>
                {
                    b.HasOne("Data.Modelos.Provincia", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Modelos.Departamento", b =>
                {
                    b.Navigation("Provincias");
                });

            modelBuilder.Entity("Data.Modelos.Provincia", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
